### ISSUE TITLE
Captcha is introduced in the website. How to bypass that ?

### ISSUE THREAD

**Issue by raghavddps2** [TechGeekMe/MSRIT-Results#3]
I tried few python packages for solving captcha, but again i am unable to do it. When you guys made it, was there any captcha in the website ?

Looking at the code here, i don't think it was, so, any ways to resolve it ?

**Comment by shoaib30** [comment]
Hi,
Captcha was introduced towards the end but the implementation was flawed. We bypassed it by using the same session cookie for every request.

1. Enter captcha once manually in the browser and check results for one candidate
2. Copy the session cookie created after entering the captcha
3. Use the cookie with all requests

I am not sure if they fixed the implementation of the captcha now. Earlier we could check one candidate's results and press back and the captcha would remain the same. Unless we refreshed the page the captcha wouldn't change.

**Comment by raghavddps2** [comment]
> Hi,
> Captcha was introduced towards the end but the implementation was flawed. We bypassed it by using the same session cookie for every request.
> 
>     1. Enter captcha once manually in the browser and check results for one candidate
> 
>     2. Copy the session cookie created after entering the captcha
> 
>     3. Use the cookie with all requests
> 
> 
> I am not sure if they fixed the implementation of the captcha now. Earlier we could check one candidate's results and press back and the captcha would remain the same. Unless we refreshed the page the captcha wouldn't change.

Oh okay, got it. They haven't fixed the implementation though. The session cookie one was a really smart one. Thank you!!
